### ISSUE TITLE
Not enabled by default for sass files.

### ISSUE THREAD

**Issue by Sureiya** [P233/Syntax-highlighting-for-Sass#25]
I'm having a problem where its not working for .sass files. I need to go into the command palette and set the syntax manually. It works fine for scss. 

I'm using build 3053.

**Comment by thiagodebastos** [comment]
For some reason the only way I can get this package to work is by manually setting it from the bottom status are right menu (open current extension as). Selecting 'open all files with current extension as' doesn't work.

**Comment by montchr** [comment]
@thiagodebastos Thanks for the tip mentioned in your edit. I just installed Seti and was wondering why my SASS files weren't using the correct syntax highlighting.

**Comment by thiagodebastos** [comment]
@montchr I'm so glad it helped someone!

**Comment by sir-dunxalot** [comment]
I know this is an old issue but since Seti UI and ST3 were mentioned, the solution for me was to open a sass or scss file being incorrectly highlighted (despite being identified by the theme correctly) and using ST's default Sass highlighting:

![image](https://cloud.githubusercontent.com/assets/4495352/7686951/a03b9df4-fd67-11e4-9502-c077ba15809f.png)

**Comment by sveggiani** [comment]
After hours of trying different things, I discovered that the Cyanide theme was "providing" a SCSS syntax highlight that doesn't allows this package to be set as the default syntax highlighter. I disabled/removed the theme and worked like a charm!

**Comment by P233** [comment]
Sorry, there is a new Sublime Text 3 version available, so I am going to close this old issue :(
