### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ivancuric** [P233/Syntax-highlighting-for-Sass#55]
Is this project still being maintained?

**Comment by CNSKnight** [comment]
idk - looks dead

**Comment by ivancuric** [comment]
So far it's been the best syntax highlighting library for SCSS, but theme makers are moving on to the new highlighting syntax which breaks this one :(

**Comment by CNSKnight** [comment]
cool - can you point us to one that works :|

**Comment by thewino** [comment]
anyone??

**Comment by P233** [comment]
I am consider to rebulid this package with the [new Sublime Text 3 syntax format](https://www.sublimetext.com/docs/3/syntax.html) and remove all completion settings because it makes this package too difficult to maintain. 

Actually, I already started a little bit:
![screen shot 2016-05-31 at 8 59 46 pm](https://cloud.githubusercontent.com/assets/1818679/15675123/f2d10d34-2772-11e6-82c9-913cec0448ff.png)
It may takes a week to finish. 

Thanks for everyone who cares about this project and I am very very sorry for the silence in the past year.

**Comment by CNSKnight** [comment]
Awesome @P233 - We're all behind you and looking forward to a great new package and thanks for your efforts!

**Comment by ivancuric** [comment]
Awesome! Welcome back!
Nothing to be sorry about, it's not like it's your obligation, plus anyone could've learned the syntax and fork the project.

As for the completions, I only use emmet css snippets, but losing `@include` and such would be a bummer :(

**Comment by gabrielmaldi** [comment]
Great! I'd love to use the new package if you release it. Thank you! 😃

**Comment by TLMcode** [comment]
anything yet? package doesn't seem to work with ST3 at all for me..

**Comment by P233** [comment]
I apologise for my late reply. Finally, I have rewritten this package and published a Sublime Text 3 only version.

Yes, it's still maintained.
