### ISSUE TITLE
Since the recent update of this package no colon ':' is added to CSS when tab completing

### ISSUE THREAD

**Issue by alanfluff** [P233/Syntax-highlighting-for-Sass#70]
Since the recent update of this package no colon ':' is added to CSS when tab completing.

EG before I would type:

`font-si` [TAB]

and

`font-size: `

would be auto inserted.

Now the colon is not auto inserted.

I have nuked ST3 back to default install and only installed this one package and the problem still exists.

I have tried uncommenting each of the last three in turn to see if any of them allows the problem to go away:

```
{
	"ignored_packages":
	[
		"Vintage",
		"SHS-At-Rule",
		"SHS-Bourbon",
		"SHS-Bourbon-Neat",
		"SHS-Compass-Mixins",
		"SHS-Compass-Variables",
		"SHS-CSS-Properties",
		"SHS-CSS-Property-Values",
		// "SHS-Sass-Functions"
	]
}
```

No different.

Until a fix, is there a way I can set the previous version of this package to not auto-update for now?

If there's and more info I can provide or other help I can offer to help find a fix, please just let me know.

Thanks, cheers!

**Comment by alanfluff** [comment]
<sub>b</sub><sup>U</sup><sub>m</sub><sup>P</sup> ^_^

**Comment by NemoAlex** [comment]
Since version 1.0, this project removed built-in completions. So the feature you mentioned has gone.
Author recommend us to use Emmet instead.
Currently there is no convenient way to install old version. 
If you have to, follow this:

1. Remove this package from package control
2. Find the `Packages` folder: Click `Preferences` - `Browse Packages`
3. Clone this project to the folder: `git clone https://github.com/P233/Syntax-highlighting-for-Sass.git`
4. Switch to a older commit: `git checkout f8af631e38e7024537941d65fb224da3c9985e3b`
5. Restart Sublime Text

**Comment by alanfluff** [comment]
@NemoAlex Thanks for pointing that out about auto completions, I missed it.

Will try Emmet again. I did try it and it didn't help :/ Maybe it's something else conflicting.

Thanks for the steps re the old version too. Much appreciated.

**Comment by alanfluff** [comment]
Tried Emmet. Did not solve. Most expansions did nothing and those that did did not add a `:` so for example: `col[tab key]` did not get me `color: `.

However, removed Emmet, returned to earlier version via @NemoAlex [VERY helpful instructions](https://github.com/P233/Syntax-highlighting-for-Sass/issues/70#issuecomment-351266187) and now glorious auto-complete is richly suggesting any and all CSS rules and upon `TAB` is completing them with a `: `.

Perfect. Thanks again @NemoAlex 👍
