### ISSUE TITLE
Goto Symbol for tag names / class names not working

### ISSUE THREAD

**Issue by mikevaux** [P233/Syntax-highlighting-for-Sass#73]
Hey,

Since updating ~~to `1.2.0`~~ recently (see below comment for clarification), goto symbol for tag names and class names have stopped working.

I created a reduced case `.scss` file to test, and in the following, only `rem` shows up as a goto definition (whereas before, `rem`, `h1` and `.something` would all have shown up.

```
$base-font-size: 16;

@function rem($size) {
    @return $size / $base-font-size * 1rem;
}

h1 { color: red; }

.something { color: blue; }
```

 - **Sublime Text:** 3.0 (3143)
 - **OS:** OS X 10.12.6

Hope that makes sense? Let me know if you need any more information! :-)

**Comment by mikevaux** [comment]
Ah, just a quick clarification - I hadn't realised there had been quite a few releases over the past few weeks; I had just realised it had been updated because of your super helpful package control message :) It may well be that it stopped working as of `1.0.0` as I haven't been writing SASS much over the last few weeks.

**Comment by P233** [comment]
The "Goto Symbol" feature for tags and classes is not supported in the latest version because of #68. If you are not worried about a messy symbols list, you could create a `.tmPreferences` file in your Sublime Text settings folder and contain the following code
https://github.com/P233/Syntax-highlighting-for-Sass/commit/2f481f456a61b30fe8c886cfeb550efdb21f23f1

**Comment by mikevaux** [comment]
Ah, interesting, ok. Thanks a lot for the reference and code! I might have a go at that in the new year; being able to use Goto Symbol for tags / class names is quite important for me.

Thanks again! :)
