### ISSUE TITLE
Highlighting Is Incorrect for CSS Property table-layout

### ISSUE THREAD

**Issue by radicalbender** [P233/Syntax-highlighting-for-Sass#74]
When setting the `table-layout` property with this syntax highlighting, it highlights "`table`" as if it were an element declaration.

Screenshot:
![leaderboards scss purdue 2018-01-15 10-57-13](https://user-images.githubusercontent.com/3972/34953635-0ab2a9dc-f9e3-11e7-90e5-ee8a298f2e40.png)

Sublime Text 3.0, Build 3143

**Comment by P233** [comment]
It's a little bit strange because `table-layout` is matched as "property name" in the latest version.

![screen shot 2018-01-16 at 19 07 14](https://user-images.githubusercontent.com/1818679/34985977-dfe9c99c-faf0-11e7-81fb-a523593ec442.png)

Sorry, I am not sure how it happens. Would you mind to double check if this package is the only active highlighting package for your file?

**Comment by radicalbender** [comment]
Oh bollocks. Sorry, I just discovered that I was looking at it with the wrong syntax highlighter. This is WAI, sorry about that.
